spring.application.name=BankManagementSystem

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:mysql://root:DAlgoNhRIeBfTzUYcEBlkFNGDEfAdQqP@zephyr.proxy.rlwy.net:20046/railway

spring.datasource.username=root
spring.datasource.password=DAlgoNhRIeBfTzUYcEBlkFNGDEfAdQqP
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect